create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text unique not null,
  password text not null,
  cedula text unique,
  phone text,
  role text not null default 'persona' check (role in ('admin', 'persona')),
  language text default 'es',
  active boolean not null default false,
  sharing_location boolean not null default false,
  last_connection timestamptz default now(),
  created_at timestamptz default now()
);

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  created_by bigint not null references public.profiles(id) on delete cascade,
  created_at timestamptz default now()
);

create table if not exists public.group_members (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  user_id bigint references public.profiles(id) on delete cascade,
  full_name text not null,
  email text not null,
  phone text not null,
  cedula text,
  relation text not null,
  location_status text not null default 'paused'
    check (location_status in ('sharing', 'paused', 'offline')),
  last_location text default 'Sin ubicacion',
  last_update timestamptz default now(),
  marker_top text default '50%',
  marker_left text default '50%',
  created_at timestamptz default now(),
  unique (group_id, email)
);

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  group_id bigint references public.groups(id) on delete cascade,
  city text default 'Quito',
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy double precision check (accuracy is null or accuracy >= 0),
  heading double precision,
  speed double precision,
  sharing boolean not null default true,
  address text,
  sector text,
  updated_at timestamptz default now()
);

create index if not exists locations_group_updated_idx
  on public.locations (group_id, updated_at desc);
create index if not exists locations_user_updated_idx
  on public.locations (user_id, updated_at desc);
create index if not exists profiles_email_idx
  on public.profiles (email);
create index if not exists group_members_group_id_idx
  on public.group_members (group_id);
create index if not exists group_members_user_id_idx
  on public.group_members (user_id);

create or replace view public.latest_user_locations as
select distinct on (user_id, group_id)
  id, user_id, group_id, latitude, longitude, accuracy, heading, speed,
  sharing, address, sector, updated_at
from public.locations
order by user_id, group_id, updated_at desc;

alter table public.profiles enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.locations enable row level security;

-- Datos academicos de demostracion. Las contrasenas se mantienen en texto plano
-- solo para compatibilidad con el login simulado actual. Antes de produccion se
-- debe migrar a Supabase Auth o hashes seguros.
insert into public.profiles
  (id, full_name, email, password, cedula, phone, role, language, active, sharing_location)
values
  (1, 'Administrador GeoKipu', 'admin@geokipu.com', 'Admin123', '1710034065', '0991234567', 'admin', 'es', true, false),
  (2, 'Persona Demo GeoKipu', 'persona@geokipu.com', 'Persona123', '0926687856', '0987654321', 'persona', 'es', true, true),
  (3, 'Camila Torres', 'camila.torres@example.com', 'Camila123', '1710000017', '0971112233', 'persona', 'es', false, false)
on conflict (id) do update set
  full_name = excluded.full_name,
  email = excluded.email,
  password = excluded.password,
  role = excluded.role;

insert into public.groups (id, name, description, created_by)
values (1, 'Familia', 'Grupo familiar para seguimiento consentido', 2)
on conflict (id) do nothing;

insert into public.group_members
  (id, group_id, user_id, full_name, email, phone, cedula, relation, location_status, last_location)
values
  (1, 1, 2, 'Persona Demo GeoKipu', 'persona@geokipu.com', '0987654321', '0926687856', 'Yo', 'sharing', 'La Carolina - Quito'),
  (2, 1, 3, 'Camila Torres', 'camila.torres@example.com', '0971112233', '1710000017', 'Hermana', 'paused', 'Cumbaya - Quito')
on conflict (id) do update set
  full_name = excluded.full_name,
  email = excluded.email,
  location_status = excluded.location_status;

insert into public.locations
  (id, user_id, group_id, latitude, longitude, accuracy, sharing, address, sector)
values
  (1, 2, 1, -0.1807, -78.4678, 15, true, 'La Carolina - Quito', 'La Carolina'),
  (2, 3, 1, -0.2009, -78.4335, 20, false, 'Cumbaya - Quito', 'Cumbaya')
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.profiles', 'id'), coalesce(max(id), 1)) from public.profiles;
select setval(pg_get_serial_sequence('public.groups', 'id'), coalesce(max(id), 1)) from public.groups;
select setval(pg_get_serial_sequence('public.group_members', 'id'), coalesce(max(id), 1)) from public.group_members;
select setval(pg_get_serial_sequence('public.locations', 'id'), coalesce(max(id), 1)) from public.locations;

-- El backend accede con SUPABASE_SERVICE_ROLE_KEY, que omite RLS. Nunca exponer
-- esa clave en Amplify, el frontend o una coleccion Postman compartida.
